version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage

  app:
    build:
      context: .
    container_name: streamlit-app
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - qdrant

  dashboard:
    build:
      context: .
    container_name: qdrant-dashboard
    ports:
      - "8502:8501"
    command: streamlit run qdrant_dashboard.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - qdrant

volumes:
  qdrant_data:
